### ISSUE TITLE
Add custom scripts to MV2 Webextension

### ISSUE THREAD

**Issue by poorejc** [UMD-ARLIS/incubator-flagon-useralejs#11]
We need to add UserALE.js filters to the Webextension so that we don't log EVERYTHING.

Example Custom Script: 

```Javascript
window.userale.filter(function (log) {
    var type_array = ['mouseup', 'mouseover', 'mousedown', 'keydown', 'dblclick', 'blur', 'focus', 'input', 'wheel'];
    var logType_array = ['interval'];
    return !type_array.includes(log.type) && !logType_array.includes(log.logType);
});
```

Note objects like "window" may not exist.

Investigate whether these should be added directly to Background or Content pages, or attached as other scripts. 

https://developer.chrome.com/docs/extensions/mv2/getstarted/

**Comment by poorejc** [comment]
add ref to 'custom.js' in rollup.config.js @ https://github.com/UMD-ARLIS/incubator-flagon-useralejs/blob/534ff9ff3e6586d1cf1d5b9718945d46479a3af3/rollup.config.js#L67

in order to appropriately transpile custom script

**Comment by poorejc** [comment]
see also: https://github.com/UMD-ARLIS/incubator-flagon-useralejs/issues/12#issuecomment-1244277428

**Comment by poorejc** [comment]
try using https://github.com/UMD-ARLIS/incubator-flagon-useralejs/blob/534ff9ff3e6586d1cf1d5b9718945d46479a3af3/example/webpackUserAleExample/index.js#L49

as example for scripting useralejs API call from 'custom.js'

**Comment by amirmghaemi** [comment]
The custom filter should be working now! You were right, the issue was rooting from the fact that it wasn't transpiling correctly! I just pushed MV2 up, and will work on MV3 now.
