### ISSUE TITLE
Add custom scripts to MV3 Webextension

### ISSUE THREAD

**Issue by poorejc** [UMD-ARLIS/incubator-flagon-useralejs#12]
We need to add UserALE.js filters to the Webextension so that we don't log EVERYTHING.

Example Custom Script: 

```Javascript
window.userale.filter(function (log) {
    var type_array = ['mouseup', 'mouseover', 'mousedown', 'keydown', 'dblclick', 'blur', 'focus', 'input', 'wheel'];
    var logType_array = ['interval'];
    return !type_array.includes(log.type) && !logType_array.includes(log.logType);
});
```

Note objects like "window" may not exist.

Investigate whether these should be added directly to Background or Content pages, or attached as other scripts. 

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by poorejc** [comment]
I think this will ignore 'content.js', which actually does stuff:

```
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": ["custom.js"],
      "all_frames": true
    }
```

Have you tried:

```
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": ["custom.js", "content.js"],
      "all_frames": true
    }
```

**Comment by amirmghaemi** [comment]
Yes, I tried that. This was what I had at first and it was working. However, when I tested it the next day, it was no longer working. 

I actually came across that same stackoverflow last week!

**Comment by amirmghaemi** [comment]
This ticket can also be closed now.
