### ISSUE TITLE
OTel Experiment 1: Check if Page Body Clicks Generate Trace IDs

### ISSUE THREAD

**Issue by alexveerasammy** [UMD-ARLIS/incubator-flagon-useralejs#5]
Currently, button clicks can generate Trace IDs. However, clicks to non-buttons should not result in a log getting written. This experiment will examine the difference in logging between button clicks and page body clicks.

**Comment by poorejc** [comment]
Yes, everything generates a traceID. TraceIds from click events are not the same traceIds generated from xmlHttpRequest, for example--EVEN if click event triggers request... Span package from xmlRequest has embedded meta data that allows for linking to a click event on a particular element.
