### ISSUE TITLE
Update Superset js/ts with UserAle.js custom script

### ISSUE THREAD

**Issue by poorejc** [UMD-ARLIS/incubator-flagon-useralejs#8]
Update Superset js/ts with UserAle.js custom script

**Comment by poorejc** [comment]
Follow example here for adding new scripts: https://github.com/UMD-ARLIS/superset/blob/2d383871a6c89f46bf0102e13c14660fe6acb9d0/arlis-added/tail_js_custom_extra.html#L1

**Comment by GoldenLambda** [comment]
To call a custom script, simply add it as a .js file somewhere in superset. Then, edit `./arlis-added/tail_js_custom_extra.html` to include a call for your script at the bottom of the file:
```  
<script
    src="YOUR FILEPATH HERE"
></script>
```
This will load whatever script you just wrote into the startup for every page in superset.

**For Example:**

In your local instance of ARLIS' Superset branch, create a new file under `./superset/arlis-added/js/lib` (the same folder that holds `userale-2.2.0.min.js`), and name it `filtermod.js`. Copy-paste the script below into your newly-created file.
```
/**
 * Initialize the options API.
 */

 const changeMe = "me";
 userale.options({
     "userId": changeMe,
     "autostart": false,
     "url": "http://localhost:9700/",
     "version": "next",
     "logDetails": True,
 });

/**
 * Filter simple inputs to focus on user interaction with browser elements.
 */

userale.filter(function (log) {
   var type_array = ['mouseup', 'mouseover', 'mousedown', 'keydown', 'blur', 'focus', 'input', 'wheel'];
   var logType_array = ['interval'];
   return !type_array.includes(log.type) && !logType_array.includes(log.logType);
});
```
When run, this script prompts userALE to take detailed logs of the user's activity in Superset, and to filter out all logs with a type listed in the array: `['mouseup', 'mouseover', 'mousedown', 'keydown', 'blur', 'focus', 'input', 'wheel']`.

Once you have created this script, you can call it by editing `tail_js_custom_extra.html` (you might have noticed it on your way to `./js/lib`) to include the following lines:
```  
<script
    src="./js/lib/filtermod.js"
 ></script>
```
Once that's all done, rebuild your superset container, pull up the userALE logs, and you will (hopefully) see that all the logs of types listed in the array have been removed from the output!
